### ISSUE TITLE
npm run pot fails

### ISSUE THREAD

**Issue by jmallach** [klembot/twinejs#500]
I recently translated twinejs to Catalan, but running it still displays quite a lot of English, so I suspect the POT is not completely up to date.

Command output:
```
⏚ [jordi:~/git/twinejs] master ± npm run pot                

> Twine@2.2.1 pot /home/jordi/git/twinejs
> node scripts/extract-pot.js

/home/jordi/git/twinejs/scripts/extract-pot.js:130
				throw new Error(`Don't know how to parse value of ${node.type}`);
				^

Error: Don't know how to parse value of TemplateLiteral
    at parseValue (/home/jordi/git/twinejs/scripts/extract-pot.js:130:11)
    at Controller.enter (/home/jordi/git/twinejs/scripts/extract-pot.js:179:8)
    at Controller.__execute (/home/jordi/git/twinejs/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/jordi/git/twinejs/node_modules/estraverse/estraverse.js:501:28)
    at Object.traverse (/home/jordi/git/twinejs/node_modules/estraverse/estraverse.js:713:27)
    at glob.sync.forEach.fileName (/home/jordi/git/twinejs/scripts/extract-pot.js:144:13)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/jordi/git/twinejs/scripts/extract-pot.js:102:26)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Twine@2.2.1 pot: `node scripts/extract-pot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Twine@2.2.1 pot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jordi/.npm/_logs/2018-11-18T08_26_03_285Z-debug.log
```
npm debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'pot' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'prepot', 'pot', 'postpot' ]
5 info lifecycle Twine@2.2.1~prepot: Twine@2.2.1
6 info lifecycle Twine@2.2.1~pot: Twine@2.2.1
7 verbose lifecycle Twine@2.2.1~pot: unsafe-perm in lifecycle true
8 verbose lifecycle Twine@2.2.1~pot: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jordi/git/twinejs/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/jordi/go/bin
9 verbose lifecycle Twine@2.2.1~pot: CWD: /home/jordi/git/twinejs
10 silly lifecycle Twine@2.2.1~pot: Args: [ '-c', 'node scripts/extract-pot.js' ]
11 silly lifecycle Twine@2.2.1~pot: Returned: code: 1  signal: null
12 info lifecycle Twine@2.2.1~pot: Failed to exec pot script
13 verbose stack Error: Twine@2.2.1 pot: `node scripts/extract-pot.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid Twine@2.2.1
15 verbose cwd /home/jordi/git/twinejs
16 verbose Linux 4.18.0-2-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "pot"
18 verbose node v9.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error Twine@2.2.1 pot: `node scripts/extract-pot.js`
22 error Exit status 1
23 error Failed at the Twine@2.2.1 pot script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cpb8010** [comment]
I added support for template literals here: https://github.com/klembot/twinejs/pull/501/commits/78cff86bd8f5c64324031850336a4eda0a5f04db

Running that on master I see 9 untranslated strings: https://github.com/cpb8010/twinejs/commit/c4b0a6d3ab2234915c920f2f181460fd4b46525a

**Comment by jmallach** [comment]
Hey @cpb8010, I don't see this commit either in master or develop, so I'm a bit confused. Was this patch ever merged?

**Comment by cpb8010** [comment]
No, it's all rolled up in my massive upgrade PR which might merge in the next version. 🤞

**Comment by jmallach** [comment]
Ah, I see. I patched up my local copy and updated the Catalan translation with the extra strings in my own PR. Thanks! 👊

**Comment by jmallach** [comment]
Oh, I see what massive PR you mean: #501! I did have a look at that one when you posted it, and I can only say: hats off, gentleman.

**Comment by jmallach** [comment]
AFAICT this is now fixed via Vue 2, so closing! 🙌
